// Generated by Haxe 4.0.0-preview.5+7eb789f54
package haxe.ds._IntMap;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public final class IntMapKeyIterator<T> extends haxe.lang.HxObject
{
	public IntMapKeyIterator(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public IntMapKeyIterator(haxe.ds.IntMap<T> m)
	{
		//line 516 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
		haxe.ds._IntMap.IntMapKeyIterator.__hx_ctor_haxe_ds__IntMap_IntMapKeyIterator(((haxe.ds._IntMap.IntMapKeyIterator<T>) (this) ), ((haxe.ds.IntMap<T>) (m) ));
	}
	
	
	protected static <T_c> void __hx_ctor_haxe_ds__IntMap_IntMapKeyIterator(haxe.ds._IntMap.IntMapKeyIterator<T_c> __hx_this, haxe.ds.IntMap<T_c> m)
	{
		//line 518 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
		__hx_this.i = 0;
		//line 519 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
		__hx_this.m = m;
		//line 520 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
		__hx_this.len = m.nBuckets;
	}
	
	
	public haxe.ds.IntMap<T> m;
	
	public int i;
	
	public int len;
	
	public final boolean hasNext()
	{
		//line 525 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
		{
			//line 525 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
			int _g = this.i;
			//line 525 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
			int _g1 = this.len;
			//line 525 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
			while (( _g < _g1 ))
			{
				//line 525 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
				int j = _g++;
				//line 527 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
				if (( (( ( this.m.flags[( j >> 4 )] >>> (( (( j & 15 )) << 1 )) ) & 3 )) == 0 )) 
				{
					//line 529 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
					this.i = j;
					//line 530 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
					return true;
				}
				
			}
			
		}
		
		//line 533 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
		return false;
	}
	
	
	public final int next()
	{
		//line 538 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
		int ret = this.m._keys[this.i];
		//line 540 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
		this.m.cachedIndex = this.i;
		//line 541 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
		this.m.cachedKey = ret;
		//line 543 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
		this.i++;
		//line 544 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
		return ret;
	}
	
	
	@Override public double __hx_setField_f(java.lang.String field, double value, boolean handleProperties)
	{
		//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
		{
			//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
			boolean __temp_executeDef1 = true;
			//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
			switch (field.hashCode())
			{
				case 107029:
				{
					//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
					if (field.equals("len")) 
					{
						//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
						__temp_executeDef1 = false;
						//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
						this.len = ((int) (value) );
						//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
						return value;
					}
					
					//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
					break;
				}
				
				
				case 105:
				{
					//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
					if (field.equals("i")) 
					{
						//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
						__temp_executeDef1 = false;
						//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
						this.i = ((int) (value) );
						//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
						return value;
					}
					
					//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
					break;
				}
				
				
			}
			
			//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
			if (__temp_executeDef1) 
			{
				//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
				return super.__hx_setField_f(field, value, handleProperties);
			}
			else
			{
				//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_setField(java.lang.String field, java.lang.Object value, boolean handleProperties)
	{
		//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
		{
			//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
			boolean __temp_executeDef1 = true;
			//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
			switch (field.hashCode())
			{
				case 107029:
				{
					//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
					if (field.equals("len")) 
					{
						//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
						__temp_executeDef1 = false;
						//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
						this.len = ((int) (haxe.lang.Runtime.toInt(value)) );
						//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
						return value;
					}
					
					//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
					break;
				}
				
				
				case 109:
				{
					//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
					if (field.equals("m")) 
					{
						//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
						__temp_executeDef1 = false;
						//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
						this.m = ((haxe.ds.IntMap<T>) (value) );
						//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
						return value;
					}
					
					//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
					break;
				}
				
				
				case 105:
				{
					//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
					if (field.equals("i")) 
					{
						//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
						__temp_executeDef1 = false;
						//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
						this.i = ((int) (haxe.lang.Runtime.toInt(value)) );
						//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
						return value;
					}
					
					//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
					break;
				}
				
				
			}
			
			//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
			if (__temp_executeDef1) 
			{
				//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
				return super.__hx_setField(field, value, handleProperties);
			}
			else
			{
				//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_getField(java.lang.String field, boolean throwErrors, boolean isCheck, boolean handleProperties)
	{
		//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
		{
			//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
			boolean __temp_executeDef1 = true;
			//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
			switch (field.hashCode())
			{
				case 3377907:
				{
					//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
					if (field.equals("next")) 
					{
						//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
						__temp_executeDef1 = false;
						//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "next")) );
					}
					
					//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
					break;
				}
				
				
				case 109:
				{
					//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
					if (field.equals("m")) 
					{
						//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
						__temp_executeDef1 = false;
						//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
						return this.m;
					}
					
					//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
					break;
				}
				
				
				case 696759469:
				{
					//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
					if (field.equals("hasNext")) 
					{
						//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
						__temp_executeDef1 = false;
						//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "hasNext")) );
					}
					
					//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
					break;
				}
				
				
				case 105:
				{
					//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
					if (field.equals("i")) 
					{
						//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
						__temp_executeDef1 = false;
						//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
						return this.i;
					}
					
					//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
					break;
				}
				
				
				case 107029:
				{
					//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
					if (field.equals("len")) 
					{
						//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
						__temp_executeDef1 = false;
						//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
						return this.len;
					}
					
					//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
					break;
				}
				
				
			}
			
			//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
			if (__temp_executeDef1) 
			{
				//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
				return super.__hx_getField(field, throwErrors, isCheck, handleProperties);
			}
			else
			{
				//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public double __hx_getField_f(java.lang.String field, boolean throwErrors, boolean handleProperties)
	{
		//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
		{
			//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
			boolean __temp_executeDef1 = true;
			//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
			switch (field.hashCode())
			{
				case 107029:
				{
					//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
					if (field.equals("len")) 
					{
						//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
						__temp_executeDef1 = false;
						//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
						return ((double) (this.len) );
					}
					
					//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
					break;
				}
				
				
				case 105:
				{
					//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
					if (field.equals("i")) 
					{
						//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
						__temp_executeDef1 = false;
						//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
						return ((double) (this.i) );
					}
					
					//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
					break;
				}
				
				
			}
			
			//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
			if (__temp_executeDef1) 
			{
				//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
				return super.__hx_getField_f(field, throwErrors, handleProperties);
			}
			else
			{
				//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_invokeField(java.lang.String field, java.lang.Object[] dynargs)
	{
		//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
		{
			//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
			boolean __temp_executeDef1 = true;
			//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
			switch (field.hashCode())
			{
				case 3377907:
				{
					//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
					if (field.equals("next")) 
					{
						//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
						__temp_executeDef1 = false;
						//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
						return this.next();
					}
					
					//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
					break;
				}
				
				
				case 696759469:
				{
					//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
					if (field.equals("hasNext")) 
					{
						//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
						__temp_executeDef1 = false;
						//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
						return this.hasNext();
					}
					
					//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
					break;
				}
				
				
			}
			
			//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
			if (__temp_executeDef1) 
			{
				//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
				return super.__hx_invokeField(field, dynargs);
			}
			else
			{
				//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public void __hx_getFields(haxe.root.Array<java.lang.String> baseArr)
	{
		//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
		baseArr.push("len");
		//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
		baseArr.push("i");
		//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
		baseArr.push("m");
		//line 510 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\haxe\\ds\\IntMap.hx"
		super.__hx_getFields(baseArr);
	}
	
	
}


