// Generated by Haxe
package haxe;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class Unserializer extends haxe.lang.HxObject
{
	static
	{
		//line 60 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
		haxe.Unserializer.DEFAULT_RESOLVER = ((java.lang.Object) (haxe.root.Type.class) );
		//line 62 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
		haxe.Unserializer.BASE64 = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789%:";
		//line 65 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
		haxe.Unserializer.CODES = null;
	}
	
	public Unserializer(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public Unserializer(java.lang.String buf)
	{
		//line 99 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
		haxe.Unserializer.__hx_ctor_haxe_Unserializer(this, buf);
	}
	
	
	public static void __hx_ctor_haxe_Unserializer(haxe.Unserializer __temp_me18, java.lang.String buf)
	{
		//line 100 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
		__temp_me18.buf = buf;
		//line 101 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
		__temp_me18.length = buf.length();
		//line 102 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
		__temp_me18.pos = 0;
		//line 106 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
		__temp_me18.scache = new haxe.root.Array<java.lang.String>();
		//line 107 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
		__temp_me18.cache = new haxe.root.Array();
		//line 108 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
		java.lang.Object r = haxe.Unserializer.DEFAULT_RESOLVER;
		//line 109 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
		if (( r == null )) 
		{
			//line 110 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
			r = haxe.root.Type.class;
			//line 111 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
			haxe.Unserializer.DEFAULT_RESOLVER = r;
		}
		
		//line 113 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
		__temp_me18.setResolver(r);
	}
	
	
	public static java.lang.Object DEFAULT_RESOLVER;
	
	public static java.lang.String BASE64;
	
	public static haxe.root.Array<java.lang.Object> CODES;
	
	public static haxe.root.Array<java.lang.Object> initCodes()
	{
		//line 72 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
		haxe.root.Array<java.lang.Object> codes = new haxe.root.Array<java.lang.Object>();
		//line 74 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
		{
			//line 74 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
			int _g1 = 0;
			//line 74 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
			int _g = haxe.Unserializer.BASE64.length();
			//line 74 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
			while (( _g1 < _g ))
			{
				//line 74 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
				int i = _g1++;
				//line 75 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
				int tmp = 0;
				//line 75 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
				java.lang.String s = haxe.Unserializer.BASE64;
				//line 75 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
				if (( i < s.length() )) 
				{
					//line 75 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					tmp = ((int) (s.charAt(i)) );
				}
				else
				{
					//line 75 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					tmp = -1;
				}
				
				//line 75 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
				codes.__set(tmp, i);
			}
			
		}
		
		//line 76 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
		return codes;
	}
	
	
	public static java.lang.Object run(java.lang.String v)
	{
		//line 460 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
		return new haxe.Unserializer(haxe.lang.Runtime.toString(v)).unserialize();
	}
	
	
	public static java.lang.Object __hx_createEmpty()
	{
		//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
		return new haxe.Unserializer(((haxe.lang.EmptyObject) (haxe.lang.EmptyObject.EMPTY) ));
	}
	
	
	public static java.lang.Object __hx_create(haxe.root.Array arr)
	{
		//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
		return new haxe.Unserializer(haxe.lang.Runtime.toString(arr.__get(0)));
	}
	
	
	public java.lang.String buf;
	
	public int pos;
	
	public int length;
	
	public haxe.root.Array cache;
	
	public haxe.root.Array<java.lang.String> scache;
	
	public java.lang.Object resolver;
	
	public void setResolver(java.lang.Object r)
	{
		//line 125 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
		if (( r == null )) 
		{
			//line 126 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
			{
				//line 127 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
				haxe.lang.Function __temp_odecl1 = ( (( haxe.Unserializer_setResolver_127__Fun.__hx_current != null )) ? (haxe.Unserializer_setResolver_127__Fun.__hx_current) : (haxe.Unserializer_setResolver_127__Fun.__hx_current = ((haxe.Unserializer_setResolver_127__Fun) (new haxe.Unserializer_setResolver_127__Fun()) )) );
				//line 128 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
				haxe.lang.Function __temp_odecl2 = ( (( haxe.Unserializer_setResolver_128__Fun.__hx_current != null )) ? (haxe.Unserializer_setResolver_128__Fun.__hx_current) : (haxe.Unserializer_setResolver_128__Fun.__hx_current = ((haxe.Unserializer_setResolver_128__Fun) (new haxe.Unserializer_setResolver_128__Fun()) )) );
				//line 126 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
				this.resolver = new haxe.lang.DynamicObject(new java.lang.String[]{"resolveClass", "resolveEnum"}, new java.lang.Object[]{__temp_odecl1, __temp_odecl2}, new java.lang.String[]{}, new double[]{});
			}
			
		}
		else
		{
			//line 131 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
			this.resolver = r;
		}
		
	}
	
	
	public int readDigits()
	{
		//line 148 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
		int k = 0;
		//line 149 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
		boolean s = false;
		//line 150 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
		int fpos = this.pos;
		//line 151 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
		while (true)
		{
			//line 152 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
			int c = 0;
			//line 152 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
			int p = this.pos;
			//line 152 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
			java.lang.String s1 = this.buf;
			//line 152 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
			if (( p < s1.length() )) 
			{
				//line 152 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
				c = ((int) (s1.charAt(p)) );
			}
			else
			{
				//line 152 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
				c = -1;
			}
			
			//line 153 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
			if (( c == -1 )) 
			{
				//line 154 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
				break;
			}
			
			//line 155 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
			if (( c == 45 )) 
			{
				//line 156 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
				if (( this.pos != fpos )) 
				{
					//line 157 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					break;
				}
				
				//line 158 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
				s = true;
				//line 159 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
				this.pos++;
				//line 160 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
				continue;
			}
			
			//line 162 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
			if (( ( c < 48 ) || ( c > 57 ) )) 
			{
				//line 163 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
				break;
			}
			
			//line 164 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
			k = ( ( k * 10 ) + (( c - 48 )) );
			//line 165 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
			this.pos++;
		}
		
		//line 167 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
		if (s) 
		{
			//line 168 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
			k *= -1;
		}
		
		//line 169 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
		return k;
	}
	
	
	public double readFloat()
	{
		//line 173 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
		int p1 = this.pos;
		//line 174 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
		while (true)
		{
			//line 175 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
			int c = 0;
			//line 175 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
			int p = this.pos;
			//line 175 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
			java.lang.String s = this.buf;
			//line 175 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
			if (( p < s.length() )) 
			{
				//line 175 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
				c = ((int) (s.charAt(p)) );
			}
			else
			{
				//line 175 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
				c = -1;
			}
			
			//line 177 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
			if (( ( ( ( c >= 43 ) && ( c < 58 ) ) || ( c == 101 ) ) || ( c == 69 ) )) 
			{
				//line 178 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
				this.pos++;
			}
			else
			{
				//line 180 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
				break;
			}
			
		}
		
		//line 182 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
		return haxe.root.Std.parseFloat(haxe.lang.StringExt.substr(this.buf, p1, ( this.pos - p1 )));
	}
	
	
	public void unserializeObject(java.lang.Object o)
	{
		//line 186 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
		while (true)
		{
			//line 187 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
			if (( this.pos >= this.length )) 
			{
				//line 188 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
				throw haxe.lang.HaxeException.wrap("Invalid object");
			}
			
			//line 189 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
			int tmp = 0;
			//line 189 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
			int p = this.pos;
			//line 189 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
			java.lang.String s = this.buf;
			//line 189 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
			if (( p < s.length() )) 
			{
				//line 189 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
				tmp = ((int) (s.charAt(p)) );
			}
			else
			{
				//line 189 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
				tmp = -1;
			}
			
			//line 189 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
			if (( tmp == 103 )) 
			{
				//line 190 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
				break;
			}
			
			//line 191 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
			java.lang.String k = haxe.lang.Runtime.toString(this.unserialize());
			//line 192 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
			if ( ! (( k instanceof java.lang.String )) ) 
			{
				//line 193 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
				throw haxe.lang.HaxeException.wrap("Invalid object key");
			}
			
			//line 194 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
			java.lang.Object v = this.unserialize();
			//line 195 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
			haxe.root.Reflect.setField(o, k, v);
		}
		
		//line 197 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
		this.pos++;
	}
	
	
	public java.lang.Object unserializeEnum(java.lang.Class edecl, java.lang.String tag)
	{
		//line 201 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
		int tmp = 0;
		//line 201 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
		int p = this.pos++;
		//line 201 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
		java.lang.String s = this.buf;
		//line 201 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
		if (( p < s.length() )) 
		{
			//line 201 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
			tmp = ((int) (s.charAt(p)) );
		}
		else
		{
			//line 201 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
			tmp = -1;
		}
		
		//line 201 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
		if (( tmp != 58 )) 
		{
			//line 202 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
			throw haxe.lang.HaxeException.wrap("Invalid enum format");
		}
		
		//line 203 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
		int nargs = this.readDigits();
		//line 204 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
		if (( nargs == 0 )) 
		{
			//line 205 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
			return ((java.lang.Object) (haxe.root.Type.createEnum(edecl, tag, null)) );
		}
		
		//line 206 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
		haxe.root.Array args = new haxe.root.Array();
		//line 207 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
		while (( nargs-- > 0 ))
		{
			//line 208 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
			args.push(this.unserialize());
		}
		
		//line 209 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
		return ((java.lang.Object) (haxe.root.Type.createEnum(edecl, tag, args)) );
	}
	
	
	public java.lang.Object unserialize()
	{
		//line 233 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
		{
			//line 233 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
			int _g = 0;
			//line 233 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
			int p = this.pos++;
			//line 233 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
			java.lang.String s = this.buf;
			//line 233 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
			if (( p < s.length() )) 
			{
				//line 233 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
				_g = ((int) (s.charAt(p)) );
			}
			else
			{
				//line 233 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
				_g = -1;
			}
			
			//line 233 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
			switch (_g)
			{
				case 110:
				{
					//line 235 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					return null;
				}
				
				
				case 116:
				{
					//line 237 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					return true;
				}
				
				
				case 102:
				{
					//line 239 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					return false;
				}
				
				
				case 122:
				{
					//line 241 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					return 0;
				}
				
				
				case 105:
				{
					//line 243 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					return this.readDigits();
				}
				
				
				case 100:
				{
					//line 245 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					return this.readFloat();
				}
				
				
				case 121:
				{
					//line 247 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					int len = this.readDigits();
					//line 248 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					boolean tmp = false;
					//line 248 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					int tmp1 = 0;
					//line 248 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					int p1 = this.pos++;
					//line 248 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					java.lang.String s1 = this.buf;
					//line 248 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					if (( p1 < s1.length() )) 
					{
						//line 248 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						tmp1 = ((int) (s1.charAt(p1)) );
					}
					else
					{
						//line 248 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						tmp1 = -1;
					}
					
					//line 248 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					if ( ! ((( tmp1 != 58 ))) ) 
					{
						//line 248 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						tmp = ( ( this.length - this.pos ) < len );
					}
					else
					{
						//line 248 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						tmp = true;
					}
					
					//line 248 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					if (tmp) 
					{
						//line 249 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						throw haxe.lang.HaxeException.wrap("Invalid string length");
					}
					
					//line 250 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					java.lang.String s2 = haxe.lang.StringExt.substr(this.buf, this.pos, len);
					//line 251 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					this.pos += len;
					//line 252 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					s2 = haxe.root.StringTools.urlDecode(s2);
					//line 253 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					this.scache.push(s2);
					//line 254 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					return s2;
				}
				
				
				case 107:
				{
					//line 256 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					return java.lang.Double.NaN;
				}
				
				
				case 109:
				{
					//line 258 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					return java.lang.Double.NEGATIVE_INFINITY;
				}
				
				
				case 112:
				{
					//line 260 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					return java.lang.Double.POSITIVE_INFINITY;
				}
				
				
				case 97:
				{
					//line 262 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					java.lang.String buf = this.buf;
					//line 263 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					haxe.root.Array a = new haxe.root.Array();
					//line 264 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					this.cache.push(a);
					//line 265 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					while (true)
					{
						//line 266 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						int c = 0;
						//line 266 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						int p2 = this.pos;
						//line 266 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						java.lang.String s3 = this.buf;
						//line 266 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						if (( p2 < s3.length() )) 
						{
							//line 266 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
							c = ((int) (s3.charAt(p2)) );
						}
						else
						{
							//line 266 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
							c = -1;
						}
						
						//line 267 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						if (( c == 104 )) 
						{
							//line 268 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
							this.pos++;
							//line 269 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
							break;
						}
						
						//line 271 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						if (( c == 117 )) 
						{
							//line 272 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
							this.pos++;
							//line 273 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
							int n = this.readDigits();
							//line 274 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
							a.__set(( ( a.length + n ) - 1 ), null);
						}
						else
						{
							//line 276 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
							a.push(this.unserialize());
						}
						
					}
					
					//line 278 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					return a;
				}
				
				
				case 111:
				{
					//line 280 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					java.lang.Object o = new haxe.lang.DynamicObject(new java.lang.String[]{}, new java.lang.Object[]{}, new java.lang.String[]{}, new double[]{});
					//line 281 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					this.cache.push(o);
					//line 282 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					this.unserializeObject(o);
					//line 283 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					return o;
				}
				
				
				case 114:
				{
					//line 285 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					int n3 = this.readDigits();
					//line 286 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					if (( ( n3 < 0 ) || ( n3 >= this.cache.length ) )) 
					{
						//line 287 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						throw haxe.lang.HaxeException.wrap("Invalid reference");
					}
					
					//line 288 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					return this.cache.__get(n3);
				}
				
				
				case 82:
				{
					//line 290 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					int n4 = this.readDigits();
					//line 291 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					if (( ( n4 < 0 ) || ( n4 >= this.scache.length ) )) 
					{
						//line 292 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						throw haxe.lang.HaxeException.wrap("Invalid string reference");
					}
					
					//line 293 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					return this.scache.__get(n4);
				}
				
				
				case 120:
				{
					//line 295 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					throw haxe.lang.HaxeException.wrap(this.unserialize());
				}
				
				
				case 99:
				{
					//line 297 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					java.lang.String name = haxe.lang.Runtime.toString(this.unserialize());
					//line 298 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					java.lang.Class cl = ((java.lang.Class) (haxe.lang.Runtime.callField(this.resolver, "resolveClass", new haxe.root.Array(new java.lang.Object[]{name}))) );
					//line 299 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					if (( ((java.lang.Object) (cl) ) == ((java.lang.Object) (null) ) )) 
					{
						//line 300 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						throw haxe.lang.HaxeException.wrap(( "Class not found " + name ));
					}
					
					//line 301 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					java.lang.Object o4 = ((java.lang.Object) (haxe.root.Type.createEmptyInstance(cl)) );
					//line 302 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					this.cache.push(o4);
					//line 303 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					this.unserializeObject(o4);
					//line 304 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					return o4;
				}
				
				
				case 119:
				{
					//line 306 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					java.lang.String name4 = haxe.lang.Runtime.toString(this.unserialize());
					//line 307 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					java.lang.Class edecl = ((java.lang.Class) (haxe.lang.Runtime.callField(this.resolver, "resolveEnum", new haxe.root.Array(new java.lang.Object[]{name4}))) );
					//line 308 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					if (( ((java.lang.Object) (edecl) ) == ((java.lang.Object) (null) ) )) 
					{
						//line 309 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						throw haxe.lang.HaxeException.wrap(( "Enum not found " + name4 ));
					}
					
					//line 310 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					java.lang.Object e = this.unserializeEnum(edecl, haxe.lang.Runtime.toString(this.unserialize()));
					//line 311 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					this.cache.push(e);
					//line 312 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					return e;
				}
				
				
				case 106:
				{
					//line 314 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					java.lang.String name5 = haxe.lang.Runtime.toString(this.unserialize());
					//line 315 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					java.lang.Class edecl5 = ((java.lang.Class) (haxe.lang.Runtime.callField(this.resolver, "resolveEnum", new haxe.root.Array(new java.lang.Object[]{name5}))) );
					//line 316 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					if (( ((java.lang.Object) (edecl5) ) == ((java.lang.Object) (null) ) )) 
					{
						//line 317 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						throw haxe.lang.HaxeException.wrap(( "Enum not found " + name5 ));
					}
					
					//line 318 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					this.pos++;
					//line 319 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					int index = this.readDigits();
					//line 320 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					java.lang.String tag = haxe.root.Type.getEnumConstructs(edecl5).__get(index);
					//line 321 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					if (( tag == null )) 
					{
						//line 322 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						throw haxe.lang.HaxeException.wrap(( ( ( "Unknown enum index " + name5 ) + "@" ) + index ));
					}
					
					//line 323 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					java.lang.Object e5 = this.unserializeEnum(edecl5, tag);
					//line 324 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					this.cache.push(e5);
					//line 325 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					return e5;
				}
				
				
				case 108:
				{
					//line 327 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					haxe.root.List l = new haxe.root.List();
					//line 328 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					this.cache.push(l);
					//line 329 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					java.lang.String buf5 = this.buf;
					//line 330 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					while (true)
					{
						//line 330 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						int tmp5 = 0;
						//line 330 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						int p5 = this.pos;
						//line 330 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						java.lang.String s5 = this.buf;
						//line 330 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						if (( p5 < s5.length() )) 
						{
							//line 330 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
							tmp5 = ((int) (s5.charAt(p5)) );
						}
						else
						{
							//line 330 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
							tmp5 = -1;
						}
						
						//line 330 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						if ( ! ((( tmp5 != 104 ))) ) 
						{
							//line 330 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
							break;
						}
						
						//line 331 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						l.add(this.unserialize());
					}
					
					//line 332 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					this.pos++;
					//line 333 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					return l;
				}
				
				
				case 98:
				{
					//line 335 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					haxe.ds.StringMap h = new haxe.ds.StringMap();
					//line 336 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					this.cache.push(h);
					//line 337 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					java.lang.String buf6 = this.buf;
					//line 338 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					while (true)
					{
						//line 338 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						int tmp6 = 0;
						//line 338 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						int p6 = this.pos;
						//line 338 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						java.lang.String s6 = this.buf;
						//line 338 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						if (( p6 < s6.length() )) 
						{
							//line 338 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
							tmp6 = ((int) (s6.charAt(p6)) );
						}
						else
						{
							//line 338 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
							tmp6 = -1;
						}
						
						//line 338 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						if ( ! ((( tmp6 != 104 ))) ) 
						{
							//line 338 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
							break;
						}
						
						//line 339 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						java.lang.String s7 = haxe.lang.Runtime.toString(this.unserialize());
						//line 340 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						h.set(s7, this.unserialize());
					}
					
					//line 342 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					this.pos++;
					//line 343 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					return h;
				}
				
				
				case 113:
				{
					//line 345 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					haxe.ds.IntMap h7 = new haxe.ds.IntMap();
					//line 346 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					this.cache.push(h7);
					//line 347 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					java.lang.String buf7 = this.buf;
					//line 348 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					int c7 = 0;
					//line 348 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					int p7 = this.pos++;
					//line 348 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					java.lang.String s8 = this.buf;
					//line 348 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					if (( p7 < s8.length() )) 
					{
						//line 348 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						c7 = ((int) (s8.charAt(p7)) );
					}
					else
					{
						//line 348 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						c7 = -1;
					}
					
					//line 349 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					while (( c7 == 58 ))
					{
						//line 350 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						int i = this.readDigits();
						//line 351 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						h7.set(i, this.unserialize());
						//line 352 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						int p8 = this.pos++;
						//line 352 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						java.lang.String s9 = this.buf;
						//line 352 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						if (( p8 < s9.length() )) 
						{
							//line 352 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
							c7 = ((int) (s9.charAt(p8)) );
						}
						else
						{
							//line 352 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
							c7 = -1;
						}
						
					}
					
					//line 354 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					if (( c7 != 104 )) 
					{
						//line 355 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						throw haxe.lang.HaxeException.wrap("Invalid IntMap format");
					}
					
					//line 356 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					return h7;
				}
				
				
				case 77:
				{
					//line 358 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					haxe.ds.ObjectMap h9 = new haxe.ds.ObjectMap();
					//line 359 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					this.cache.push(h9);
					//line 360 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					java.lang.String buf9 = this.buf;
					//line 361 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					while (true)
					{
						//line 361 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						int tmp9 = 0;
						//line 361 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						int p9 = this.pos;
						//line 361 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						java.lang.String s10 = this.buf;
						//line 361 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						if (( p9 < s10.length() )) 
						{
							//line 361 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
							tmp9 = ((int) (s10.charAt(p9)) );
						}
						else
						{
							//line 361 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
							tmp9 = -1;
						}
						
						//line 361 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						if ( ! ((( tmp9 != 104 ))) ) 
						{
							//line 361 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
							break;
						}
						
						//line 362 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						java.lang.Object s11 = this.unserialize();
						//line 363 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						h9.set(s11, this.unserialize());
					}
					
					//line 365 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					this.pos++;
					//line 366 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					return h9;
				}
				
				
				case 118:
				{
					//line 368 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					haxe.root.Date d = null;
					//line 369 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					boolean tmp11 = false;
					//line 369 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					boolean tmp12 = false;
					//line 369 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					boolean tmp13 = false;
					//line 369 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					boolean tmp14 = false;
					//line 369 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					boolean tmp15 = false;
					//line 369 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					boolean tmp16 = false;
					//line 369 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					boolean tmp17 = false;
					//line 369 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					boolean tmp18 = false;
					//line 369 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					int tmp19 = 0;
					//line 369 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					int p19 = this.pos;
					//line 369 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					java.lang.String s19 = this.buf;
					//line 369 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					if (( p19 < s19.length() )) 
					{
						//line 369 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						tmp19 = ((int) (s19.charAt(p19)) );
					}
					else
					{
						//line 369 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						tmp19 = -1;
					}
					
					//line 369 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					if (( tmp19 >= 48 )) 
					{
						//line 369 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						int tmp20 = 0;
						//line 369 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						int p20 = this.pos;
						//line 369 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						java.lang.String s20 = this.buf;
						//line 369 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						if (( p20 < s20.length() )) 
						{
							//line 369 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
							tmp20 = ((int) (s20.charAt(p20)) );
						}
						else
						{
							//line 369 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
							tmp20 = -1;
						}
						
						//line 369 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						tmp18 = ( tmp20 <= 57 );
					}
					else
					{
						//line 369 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						tmp18 = false;
					}
					
					//line 369 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					if (tmp18) 
					{
						//line 370 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						int tmp21 = 0;
						//line 370 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						int p21 = ( this.pos + 1 );
						//line 370 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						java.lang.String s21 = this.buf;
						//line 370 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						if (( p21 < s21.length() )) 
						{
							//line 370 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
							tmp21 = ((int) (s21.charAt(p21)) );
						}
						else
						{
							//line 370 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
							tmp21 = -1;
						}
						
						//line 370 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						tmp17 = ( tmp21 >= 48 );
					}
					else
					{
						//line 369 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						tmp17 = false;
					}
					
					//line 369 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					if (tmp17) 
					{
						//line 370 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						int tmp22 = 0;
						//line 370 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						int p22 = ( this.pos + 1 );
						//line 370 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						java.lang.String s22 = this.buf;
						//line 370 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						if (( p22 < s22.length() )) 
						{
							//line 370 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
							tmp22 = ((int) (s22.charAt(p22)) );
						}
						else
						{
							//line 370 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
							tmp22 = -1;
						}
						
						//line 370 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						tmp16 = ( tmp22 <= 57 );
					}
					else
					{
						//line 369 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						tmp16 = false;
					}
					
					//line 369 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					if (tmp16) 
					{
						//line 371 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						int tmp23 = 0;
						//line 371 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						int p23 = ( this.pos + 2 );
						//line 371 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						java.lang.String s23 = this.buf;
						//line 371 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						if (( p23 < s23.length() )) 
						{
							//line 371 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
							tmp23 = ((int) (s23.charAt(p23)) );
						}
						else
						{
							//line 371 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
							tmp23 = -1;
						}
						
						//line 371 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						tmp15 = ( tmp23 >= 48 );
					}
					else
					{
						//line 369 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						tmp15 = false;
					}
					
					//line 369 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					if (tmp15) 
					{
						//line 371 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						int tmp24 = 0;
						//line 371 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						int p24 = ( this.pos + 2 );
						//line 371 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						java.lang.String s24 = this.buf;
						//line 371 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						if (( p24 < s24.length() )) 
						{
							//line 371 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
							tmp24 = ((int) (s24.charAt(p24)) );
						}
						else
						{
							//line 371 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
							tmp24 = -1;
						}
						
						//line 371 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						tmp14 = ( tmp24 <= 57 );
					}
					else
					{
						//line 369 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						tmp14 = false;
					}
					
					//line 369 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					if (tmp14) 
					{
						//line 372 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						int tmp25 = 0;
						//line 372 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						int p25 = ( this.pos + 3 );
						//line 372 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						java.lang.String s25 = this.buf;
						//line 372 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						if (( p25 < s25.length() )) 
						{
							//line 372 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
							tmp25 = ((int) (s25.charAt(p25)) );
						}
						else
						{
							//line 372 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
							tmp25 = -1;
						}
						
						//line 372 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						tmp13 = ( tmp25 >= 48 );
					}
					else
					{
						//line 369 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						tmp13 = false;
					}
					
					//line 369 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					if (tmp13) 
					{
						//line 372 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						int tmp26 = 0;
						//line 372 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						int p26 = ( this.pos + 3 );
						//line 372 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						java.lang.String s26 = this.buf;
						//line 372 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						if (( p26 < s26.length() )) 
						{
							//line 372 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
							tmp26 = ((int) (s26.charAt(p26)) );
						}
						else
						{
							//line 372 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
							tmp26 = -1;
						}
						
						//line 372 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						tmp12 = ( tmp26 <= 57 );
					}
					else
					{
						//line 369 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						tmp12 = false;
					}
					
					//line 369 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					if (tmp12) 
					{
						//line 373 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						int tmp27 = 0;
						//line 373 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						int p27 = ( this.pos + 4 );
						//line 373 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						java.lang.String s27 = this.buf;
						//line 373 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						if (( p27 < s27.length() )) 
						{
							//line 373 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
							tmp27 = ((int) (s27.charAt(p27)) );
						}
						else
						{
							//line 373 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
							tmp27 = -1;
						}
						
						//line 373 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						tmp11 = ( tmp27 == 45 );
					}
					else
					{
						//line 369 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						tmp11 = false;
					}
					
					//line 369 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					if (tmp11) 
					{
						//line 376 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						d = haxe.root.Date.fromString(haxe.lang.StringExt.substr(this.buf, this.pos, 19));
						//line 377 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						this.pos += 19;
					}
					else
					{
						//line 379 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						d = haxe.root.Date.fromTime(this.readFloat());
					}
					
					//line 380 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					this.cache.push(d);
					//line 381 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					return d;
				}
				
				
				case 115:
				{
					//line 383 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					int len27 = this.readDigits();
					//line 384 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					java.lang.String buf27 = this.buf;
					//line 385 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					boolean tmp28 = false;
					//line 385 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					int tmp29 = 0;
					//line 385 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					int p29 = this.pos++;
					//line 385 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					java.lang.String s29 = this.buf;
					//line 385 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					if (( p29 < s29.length() )) 
					{
						//line 385 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						tmp29 = ((int) (s29.charAt(p29)) );
					}
					else
					{
						//line 385 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						tmp29 = -1;
					}
					
					//line 385 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					if ( ! ((( tmp29 != 58 ))) ) 
					{
						//line 385 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						tmp28 = ( ( this.length - this.pos ) < len27 );
					}
					else
					{
						//line 385 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						tmp28 = true;
					}
					
					//line 385 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					if (tmp28) 
					{
						//line 386 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						throw haxe.lang.HaxeException.wrap("Invalid bytes length");
					}
					
					//line 390 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					haxe.root.Array<java.lang.Object> codes = haxe.Unserializer.CODES;
					//line 391 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					if (( codes == null )) 
					{
						//line 392 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						codes = haxe.Unserializer.initCodes();
						//line 393 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						haxe.Unserializer.CODES = codes;
					}
					
					//line 395 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					int i29 = this.pos;
					//line 396 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					int rest = ( len27 & 3 );
					//line 397 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					int size = ( ( (( len27 >> 2 )) * 3 ) + (( (( rest >= 2 )) ? (( rest - 1 )) : (0) )) );
					//line 398 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					int max = ( i29 + (( len27 - rest )) );
					//line 399 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					haxe.io.Bytes bytes = haxe.io.Bytes.alloc(size);
					//line 400 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					int bpos = 0;
					//line 401 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					while (( i29 < max ))
					{
						//line 402 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						int tmp30 = 0;
						//line 402 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						int index30 = i29++;
						//line 402 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						if (( index30 < buf27.length() )) 
						{
							//line 402 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
							tmp30 = ((int) (buf27.charAt(index30)) );
						}
						else
						{
							//line 402 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
							tmp30 = -1;
						}
						
						//line 402 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						int c1 = ((int) (haxe.lang.Runtime.toInt(codes.__get(tmp30))) );
						//line 403 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						int tmp31 = 0;
						//line 403 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						int index31 = i29++;
						//line 403 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						if (( index31 < buf27.length() )) 
						{
							//line 403 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
							tmp31 = ((int) (buf27.charAt(index31)) );
						}
						else
						{
							//line 403 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
							tmp31 = -1;
						}
						
						//line 403 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						int c2 = ((int) (haxe.lang.Runtime.toInt(codes.__get(tmp31))) );
						//line 404 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						bytes.b[bpos++] = ((byte) (( ( c1 << 2 ) | ( c2 >> 4 ) )) );
						//line 405 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						int tmp32 = 0;
						//line 405 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						int index32 = i29++;
						//line 405 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						if (( index32 < buf27.length() )) 
						{
							//line 405 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
							tmp32 = ((int) (buf27.charAt(index32)) );
						}
						else
						{
							//line 405 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
							tmp32 = -1;
						}
						
						//line 405 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						int c3 = ((int) (haxe.lang.Runtime.toInt(codes.__get(tmp32))) );
						//line 406 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						bytes.b[bpos++] = ((byte) (( ( c2 << 4 ) | ( c3 >> 2 ) )) );
						//line 407 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						int tmp33 = 0;
						//line 407 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						int index33 = i29++;
						//line 407 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						if (( index33 < buf27.length() )) 
						{
							//line 407 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
							tmp33 = ((int) (buf27.charAt(index33)) );
						}
						else
						{
							//line 407 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
							tmp33 = -1;
						}
						
						//line 407 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						int c4 = ((int) (haxe.lang.Runtime.toInt(codes.__get(tmp33))) );
						//line 408 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						bytes.b[bpos++] = ((byte) (( ( c3 << 6 ) | c4 )) );
					}
					
					//line 410 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					if (( rest >= 2 )) 
					{
						//line 411 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						int tmp34 = 0;
						//line 411 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						int index34 = i29++;
						//line 411 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						if (( index34 < buf27.length() )) 
						{
							//line 411 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
							tmp34 = ((int) (buf27.charAt(index34)) );
						}
						else
						{
							//line 411 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
							tmp34 = -1;
						}
						
						//line 411 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						int c134 = ((int) (haxe.lang.Runtime.toInt(codes.__get(tmp34))) );
						//line 412 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						int tmp35 = 0;
						//line 412 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						int index35 = i29++;
						//line 412 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						if (( index35 < buf27.length() )) 
						{
							//line 412 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
							tmp35 = ((int) (buf27.charAt(index35)) );
						}
						else
						{
							//line 412 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
							tmp35 = -1;
						}
						
						//line 412 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						int c235 = ((int) (haxe.lang.Runtime.toInt(codes.__get(tmp35))) );
						//line 413 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						bytes.b[bpos++] = ((byte) (( ( c134 << 2 ) | ( c235 >> 4 ) )) );
						//line 414 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						if (( rest == 3 )) 
						{
							//line 415 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
							int tmp36 = 0;
							//line 415 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
							int index36 = i29++;
							//line 415 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
							if (( index36 < buf27.length() )) 
							{
								//line 415 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
								tmp36 = ((int) (buf27.charAt(index36)) );
							}
							else
							{
								//line 415 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
								tmp36 = -1;
							}
							
							//line 415 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
							int c336 = ((int) (haxe.lang.Runtime.toInt(codes.__get(tmp36))) );
							//line 416 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
							bytes.b[bpos++] = ((byte) (( ( c235 << 4 ) | ( c336 >> 2 ) )) );
						}
						
					}
					
					//line 420 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					this.pos += len27;
					//line 421 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					this.cache.push(bytes);
					//line 422 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					return bytes;
				}
				
				
				case 67:
				{
					//line 424 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					java.lang.String name36 = haxe.lang.Runtime.toString(this.unserialize());
					//line 425 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					java.lang.Class cl36 = ((java.lang.Class) (haxe.lang.Runtime.callField(this.resolver, "resolveClass", new haxe.root.Array(new java.lang.Object[]{name36}))) );
					//line 426 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					if (( ((java.lang.Object) (cl36) ) == ((java.lang.Object) (null) ) )) 
					{
						//line 427 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						throw haxe.lang.HaxeException.wrap(( "Class not found " + name36 ));
					}
					
					//line 428 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					java.lang.Object o36 = ((java.lang.Object) (haxe.root.Type.createEmptyInstance(cl36)) );
					//line 429 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					this.cache.push(o36);
					//line 430 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					haxe.lang.Runtime.callField(o36, "hxUnserialize", new haxe.root.Array(new java.lang.Object[]{this}));
					//line 431 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					int tmp37 = 0;
					//line 431 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					int p37 = this.pos++;
					//line 431 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					java.lang.String s37 = this.buf;
					//line 431 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					if (( p37 < s37.length() )) 
					{
						//line 431 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						tmp37 = ((int) (s37.charAt(p37)) );
					}
					else
					{
						//line 431 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						tmp37 = -1;
					}
					
					//line 431 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					if (( tmp37 != 103 )) 
					{
						//line 432 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						throw haxe.lang.HaxeException.wrap("Invalid custom data");
					}
					
					//line 433 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					return o36;
				}
				
				
				case 65:
				{
					//line 435 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					java.lang.String name37 = haxe.lang.Runtime.toString(this.unserialize());
					//line 436 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					java.lang.Class cl37 = ((java.lang.Class) (haxe.lang.Runtime.callField(this.resolver, "resolveClass", new haxe.root.Array(new java.lang.Object[]{name37}))) );
					//line 437 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					if (( ((java.lang.Object) (cl37) ) == ((java.lang.Object) (null) ) )) 
					{
						//line 438 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						throw haxe.lang.HaxeException.wrap(( "Class not found " + name37 ));
					}
					
					//line 439 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					return cl37;
				}
				
				
				case 66:
				{
					//line 441 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					java.lang.String name38 = haxe.lang.Runtime.toString(this.unserialize());
					//line 442 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					java.lang.Class e38 = ((java.lang.Class) (haxe.lang.Runtime.callField(this.resolver, "resolveEnum", new haxe.root.Array(new java.lang.Object[]{name38}))) );
					//line 443 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					if (( ((java.lang.Object) (e38) ) == ((java.lang.Object) (null) ) )) 
					{
						//line 444 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						throw haxe.lang.HaxeException.wrap(( "Enum not found " + name38 ));
					}
					
					//line 445 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					return e38;
				}
				
				
				default:
				{
					//line 233 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					break;
				}
				
			}
			
		}
		
		//line 448 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
		this.pos--;
		//line 449 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
		throw haxe.lang.HaxeException.wrap(( ( ( "Invalid char " + haxe.lang.StringExt.charAt(this.buf, this.pos) ) + " at position " ) + this.pos ));
	}
	
	
	@Override public double __hx_setField_f(java.lang.String field, double value, boolean handleProperties)
	{
		//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
		{
			//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
			boolean __temp_executeDef1 = true;
			//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
			switch (field.hashCode())
			{
				case -341328890:
				{
					//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					if (field.equals("resolver")) 
					{
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						__temp_executeDef1 = false;
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						this.resolver = ((java.lang.Object) (value) );
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						return value;
					}
					
					//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					break;
				}
				
				
				case 111188:
				{
					//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					if (field.equals("pos")) 
					{
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						__temp_executeDef1 = false;
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						this.pos = ((int) (value) );
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						return value;
					}
					
					//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					break;
				}
				
				
				case -1106363674:
				{
					//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					if (field.equals("length")) 
					{
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						__temp_executeDef1 = false;
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						this.length = ((int) (value) );
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						return value;
					}
					
					//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					break;
				}
				
				
			}
			
			//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
			if (__temp_executeDef1) 
			{
				//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
				return super.__hx_setField_f(field, value, handleProperties);
			}
			else
			{
				//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_setField(java.lang.String field, java.lang.Object value, boolean handleProperties)
	{
		//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
		{
			//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
			boolean __temp_executeDef1 = true;
			//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
			switch (field.hashCode())
			{
				case -341328890:
				{
					//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					if (field.equals("resolver")) 
					{
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						__temp_executeDef1 = false;
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						this.resolver = ((java.lang.Object) (value) );
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						return value;
					}
					
					//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					break;
				}
				
				
				case 97907:
				{
					//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					if (field.equals("buf")) 
					{
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						__temp_executeDef1 = false;
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						this.buf = haxe.lang.Runtime.toString(value);
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						return value;
					}
					
					//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					break;
				}
				
				
				case -908198161:
				{
					//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					if (field.equals("scache")) 
					{
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						__temp_executeDef1 = false;
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						this.scache = ((haxe.root.Array<java.lang.String>) (value) );
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						return value;
					}
					
					//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					break;
				}
				
				
				case 111188:
				{
					//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					if (field.equals("pos")) 
					{
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						__temp_executeDef1 = false;
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						this.pos = ((int) (haxe.lang.Runtime.toInt(value)) );
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						return value;
					}
					
					//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					break;
				}
				
				
				case 94416770:
				{
					//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					if (field.equals("cache")) 
					{
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						__temp_executeDef1 = false;
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						this.cache = ((haxe.root.Array) (value) );
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						return value;
					}
					
					//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					break;
				}
				
				
				case -1106363674:
				{
					//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					if (field.equals("length")) 
					{
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						__temp_executeDef1 = false;
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						this.length = ((int) (haxe.lang.Runtime.toInt(value)) );
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						return value;
					}
					
					//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					break;
				}
				
				
			}
			
			//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
			if (__temp_executeDef1) 
			{
				//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
				return super.__hx_setField(field, value, handleProperties);
			}
			else
			{
				//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_getField(java.lang.String field, boolean throwErrors, boolean isCheck, boolean handleProperties)
	{
		//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
		{
			//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
			boolean __temp_executeDef1 = true;
			//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
			switch (field.hashCode())
			{
				case -505039769:
				{
					//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					if (field.equals("unserialize")) 
					{
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						__temp_executeDef1 = false;
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "unserialize")) );
					}
					
					//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					break;
				}
				
				
				case 97907:
				{
					//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					if (field.equals("buf")) 
					{
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						__temp_executeDef1 = false;
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						return this.buf;
					}
					
					//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					break;
				}
				
				
				case 1438134792:
				{
					//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					if (field.equals("unserializeEnum")) 
					{
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						__temp_executeDef1 = false;
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "unserializeEnum")) );
					}
					
					//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					break;
				}
				
				
				case 111188:
				{
					//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					if (field.equals("pos")) 
					{
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						__temp_executeDef1 = false;
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						return this.pos;
					}
					
					//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					break;
				}
				
				
				case -657057146:
				{
					//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					if (field.equals("unserializeObject")) 
					{
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						__temp_executeDef1 = false;
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "unserializeObject")) );
					}
					
					//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					break;
				}
				
				
				case -1106363674:
				{
					//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					if (field.equals("length")) 
					{
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						__temp_executeDef1 = false;
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						return this.length;
					}
					
					//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					break;
				}
				
				
				case -1136761242:
				{
					//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					if (field.equals("readFloat")) 
					{
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						__temp_executeDef1 = false;
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "readFloat")) );
					}
					
					//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					break;
				}
				
				
				case 94416770:
				{
					//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					if (field.equals("cache")) 
					{
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						__temp_executeDef1 = false;
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						return this.cache;
					}
					
					//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					break;
				}
				
				
				case -940119524:
				{
					//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					if (field.equals("readDigits")) 
					{
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						__temp_executeDef1 = false;
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "readDigits")) );
					}
					
					//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					break;
				}
				
				
				case -908198161:
				{
					//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					if (field.equals("scache")) 
					{
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						__temp_executeDef1 = false;
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						return this.scache;
					}
					
					//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					break;
				}
				
				
				case 1647991432:
				{
					//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					if (field.equals("setResolver")) 
					{
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						__temp_executeDef1 = false;
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "setResolver")) );
					}
					
					//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					break;
				}
				
				
				case -341328890:
				{
					//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					if (field.equals("resolver")) 
					{
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						__temp_executeDef1 = false;
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						return this.resolver;
					}
					
					//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					break;
				}
				
				
			}
			
			//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
			if (__temp_executeDef1) 
			{
				//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
				return super.__hx_getField(field, throwErrors, isCheck, handleProperties);
			}
			else
			{
				//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public double __hx_getField_f(java.lang.String field, boolean throwErrors, boolean handleProperties)
	{
		//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
		{
			//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
			boolean __temp_executeDef1 = true;
			//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
			switch (field.hashCode())
			{
				case -341328890:
				{
					//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					if (field.equals("resolver")) 
					{
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						__temp_executeDef1 = false;
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						return ((double) (haxe.lang.Runtime.toDouble(this.resolver)) );
					}
					
					//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					break;
				}
				
				
				case 111188:
				{
					//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					if (field.equals("pos")) 
					{
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						__temp_executeDef1 = false;
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						return ((double) (this.pos) );
					}
					
					//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					break;
				}
				
				
				case -1106363674:
				{
					//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					if (field.equals("length")) 
					{
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						__temp_executeDef1 = false;
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						return ((double) (this.length) );
					}
					
					//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					break;
				}
				
				
			}
			
			//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
			if (__temp_executeDef1) 
			{
				//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
				return super.__hx_getField_f(field, throwErrors, handleProperties);
			}
			else
			{
				//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_invokeField(java.lang.String field, haxe.root.Array dynargs)
	{
		//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
		{
			//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
			boolean __temp_executeDef1 = true;
			//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
			switch (field.hashCode())
			{
				case -505039769:
				{
					//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					if (field.equals("unserialize")) 
					{
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						__temp_executeDef1 = false;
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						return this.unserialize();
					}
					
					//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					break;
				}
				
				
				case 1647991432:
				{
					//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					if (field.equals("setResolver")) 
					{
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						__temp_executeDef1 = false;
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						this.setResolver(dynargs.__get(0));
					}
					
					//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					break;
				}
				
				
				case 1438134792:
				{
					//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					if (field.equals("unserializeEnum")) 
					{
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						__temp_executeDef1 = false;
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						return this.unserializeEnum(((java.lang.Class) (dynargs.__get(0)) ), haxe.lang.Runtime.toString(dynargs.__get(1)));
					}
					
					//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					break;
				}
				
				
				case -940119524:
				{
					//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					if (field.equals("readDigits")) 
					{
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						__temp_executeDef1 = false;
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						return this.readDigits();
					}
					
					//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					break;
				}
				
				
				case -657057146:
				{
					//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					if (field.equals("unserializeObject")) 
					{
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						__temp_executeDef1 = false;
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						this.unserializeObject(dynargs.__get(0));
					}
					
					//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					break;
				}
				
				
				case -1136761242:
				{
					//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					if (field.equals("readFloat")) 
					{
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						__temp_executeDef1 = false;
						//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
						return this.readFloat();
					}
					
					//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
					break;
				}
				
				
			}
			
			//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
			if (__temp_executeDef1) 
			{
				//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
				return super.__hx_invokeField(field, dynargs);
			}
			
		}
		
		//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
		return null;
	}
	
	
	@Override public void __hx_getFields(haxe.root.Array<java.lang.String> baseArr)
	{
		//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
		baseArr.push("resolver");
		//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
		baseArr.push("scache");
		//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
		baseArr.push("cache");
		//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
		baseArr.push("length");
		//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
		baseArr.push("pos");
		//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
		baseArr.push("buf");
		//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
		{
			//line 42 "/usr/local/lib/haxe/std/haxe/Unserializer.hx"
			super.__hx_getFields(baseArr);
		}
		
	}
	
	
}


