// Generated by Haxe 4.3.0
package haxe.io;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class Eof extends haxe.lang.HxObject
{
	public Eof(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public Eof()
	{
		//line 29 "C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\Eof.hx"
		haxe.io.Eof.__hx_ctor_haxe_io_Eof(this);
	}
	
	
	protected static void __hx_ctor_haxe_io_Eof(haxe.io.Eof __hx_this)
	{
	}
	
	
	@Override public java.lang.String toString()
	{
		//line 33 "C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\Eof.hx"
		return "Eof";
	}
	
	
	@Override public java.lang.Object __hx_getField(java.lang.String field, boolean throwErrors, boolean isCheck, boolean handleProperties)
	{
		//line 28 "C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\Eof.hx"
		{
			//line 28 "C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\Eof.hx"
			boolean __temp_executeDef1 = true;
			//line 28 "C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\Eof.hx"
			if (( field != null )) 
			{
				//line 28 "C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\Eof.hx"
				switch (field.hashCode())
				{
					case -1776922004:
					{
						//line 28 "C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\Eof.hx"
						if (field.equals("toString")) 
						{
							//line 28 "C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\Eof.hx"
							__temp_executeDef1 = false;
							//line 28 "C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\Eof.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "toString")) );
						}
						
						//line 28 "C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\Eof.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 28 "C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\Eof.hx"
			if (__temp_executeDef1) 
			{
				//line 28 "C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\Eof.hx"
				return super.__hx_getField(field, throwErrors, isCheck, handleProperties);
			}
			else
			{
				//line 28 "C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\Eof.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_invokeField(java.lang.String field, java.lang.Object[] dynargs)
	{
		//line 28 "C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\Eof.hx"
		{
			//line 28 "C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\Eof.hx"
			boolean __temp_executeDef1 = true;
			//line 28 "C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\Eof.hx"
			if (( field != null )) 
			{
				//line 28 "C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\Eof.hx"
				switch (field.hashCode())
				{
					case -1776922004:
					{
						//line 28 "C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\Eof.hx"
						if (field.equals("toString")) 
						{
							//line 28 "C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\Eof.hx"
							__temp_executeDef1 = false;
							//line 28 "C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\Eof.hx"
							return this.toString();
						}
						
						//line 28 "C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\Eof.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 28 "C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\Eof.hx"
			if (__temp_executeDef1) 
			{
				//line 28 "C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\Eof.hx"
				return super.__hx_invokeField(field, dynargs);
			}
			else
			{
				//line 28 "C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\Eof.hx"
				throw null;
			}
			
		}
		
	}
	
	
}


