org.gradle.jvmargs =-Xmx2g 
# IntelliJ Platform Artifacts Repositories
# -> https://plugins.jetbrains.com/docs/intellij/intellij-artifacts.html

pluginGroup = com.intellij.plugins.haxe
pluginName = Haxe Toolkit Support
pluginRepositoryUrl = https://github.com/HaxeFoundation/intellij-haxe

# SemVer format -> https://semver.org
pluginVersion = 1.8.0

# IntelliJ Platform Properties -> https://github.com/JetBrains/gradle-intellij-plugin#intellij-platform-properties
platformType = IU
#platformType = IC


#run print product releases to see what's the LATEST-EAP-SNAPSHOT
#platformVersion = 2025.2.5
#platformVersion = 2025.3.2
platformVersion = 261.22158.182
#platformVersion = 2026.1
platformDownloadSources = true

# See https://plugins.jetbrains.com/docs/intellij/build-number-ranges.html
# for insight into build numbers and IntelliJ Platform versions.
pluginSinceBuild = 252
pluginUntilBuild = 261.*

# Plugin Dependencies -> https://plugins.jetbrains.com/docs/intellij/plugin-dependencies.html
# Example: platformPlugins = com.intellij.java, com.jetbrains.php:203.4449.22
# versions numbers can be found at :
# flex/flash : https://plugins.jetbrains.com/plugin/14508-flash-flex/versions/stable/252411
# classic UI :  https://plugins.jetbrains.com/plugin/24468-classic-ui
# Git Modal Commit Interface  : https://plugins.jetbrains.com/plugin/26647-git-modal-commit-interface
# OpenGL-Plugin :  https://plugins.jetbrains.com/plugin/18470-glsl

# 2026.1
platformBundledPlugins = com.intellij.java, com.intellij.modules.json
platformPlugins = com.intellij.flex:261.22158.182, OpenGL-Plugin:1.1.6, com.intellij.classic.ui:261.22158.185, intellij.git.commit.modal:261.22158.41

# 2025.3
#platformBundledPlugins = com.intellij.java, com.intellij.modules.json
#platformPlugins = com.intellij.flex:253.28294.251, OpenGL-Plugin:1.1.6, com.intellij.classic.ui:253.28294.218, intellij.git.commit.modal:253.28294.256

# IC 2025.2
#platformBundledPlugins = com.intellij.java, com.intellij.modules.json
#platformPlugins = com.intellij.flex:252.23892.360, OpenGL-Plugin:1.1.6, com.intellij.classic.ui:252.23892.201, intellij.git.commit.modal:252.23892.364


# Java language level used to compile sources and to generate the files for - Java 17 is required since 2022.2
javaVersion = 21

# Gradle Releases -> https://github.com/gradle/gradle/releases
gradleVersion = 9.4.0

# Opt-out flag for bundling Kotlin standard library.
# See https://plugins.jetbrains.com/docs/intellij/kotlin.html#kotlin-standard-library for details.
# suppress inspection "UnusedProperty"
#NOTE mlo:
# - Changing this one to true for 2025.2 as a workaround for "NoSuchMethodError kotlin.sequences.Sequence" when running tests
kotlin.stdlib.default.dependency = true


#Hxcpp Debugger dependencies
hxjavaVersion=4.2.0
hxcppDebuggerGit=https://github.com/HaxeFoundation/hxcpp-debugger.git
hxcppDebuggerBranch=protocol_v1.1
generateHxcppDebugger=false

# change haxelib versions to the ones used in this build
# --always / --never
haxeLibChangeVersion=--always