/*
 * Copyright 2000-2013 JetBrains s.r.o.
 * Copyright 2014-2018 AS3Boyan
 * Copyright 2014-2014 Elias Ku
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by Haxe 3.4.7
package debugger;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class StructuredValueType extends haxe.lang.ParamEnum
{
	public StructuredValueType(int index, Object[] params)
	{
		//line 99 "C:\\HaxeToolkit\\haxe\\std\\java\\internal\\HxObject.hx"
		super(index, params);
	}
	
	
	public static final String[] __hx_constructs = new String[]{"TypeNull", "TypeBool", "TypeInt", "TypeFloat", "TypeString", "TypeInstance", "TypeEnum", "TypeAnonymous", "TypeClass", "TypeFunction", "TypeArray"};
	
	public static final StructuredValueType TypeNull = new StructuredValueType(0, null);
	
	public static final StructuredValueType TypeBool = new StructuredValueType(1, null);
	
	public static final StructuredValueType TypeInt = new StructuredValueType(2, null);
	
	public static final StructuredValueType TypeFloat = new StructuredValueType(3, null);
	
	public static final StructuredValueType TypeString = new StructuredValueType(4, null);
	
	public static StructuredValueType TypeInstance(String className)
	{
		//line 275 "C:\\HaxeToolkit\\haxe\\lib\\hxcpp-debugger\\git\\debugger\\IController.hx"
		return new StructuredValueType(5, new Object[]{className});
	}
	
	
	public static StructuredValueType TypeEnum(String enumName)
	{
		//line 276 "C:\\HaxeToolkit\\haxe\\lib\\hxcpp-debugger\\git\\debugger\\IController.hx"
		return new StructuredValueType(6, new Object[]{enumName});
	}
	
	
	public static StructuredValueType TypeAnonymous(debugger.StructuredValueTypeList elements)
	{
		//line 277 "C:\\HaxeToolkit\\haxe\\lib\\hxcpp-debugger\\git\\debugger\\IController.hx"
		return new StructuredValueType(7, new Object[]{elements});
	}
	
	
	public static StructuredValueType TypeClass(String className)
	{
		//line 278 "C:\\HaxeToolkit\\haxe\\lib\\hxcpp-debugger\\git\\debugger\\IController.hx"
		return new StructuredValueType(8, new Object[]{className});
	}
	
	
	public static final StructuredValueType TypeFunction = new StructuredValueType(9, null);
	
	public static final StructuredValueType TypeArray = new StructuredValueType(10, null);
	
	@Override public String getTag()
	{
		//line 268 "C:\\HaxeToolkit\\haxe\\lib\\hxcpp-debugger\\git\\debugger\\IController.hx"
		return StructuredValueType.__hx_constructs[this.index];
	}
	
	
}


