{
  parserClass="com.intellij.plugins.haxe.hxml.HXMLParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="HXML"
  psiImplClassSuffix="Impl"
  psiPackage="com.intellij.plugins.haxe.hxml.psi"
  psiImplPackage="com.intellij.plugins.haxe.hxml.psi.impl"

  elementTypeHolderClass="com.intellij.plugins.haxe.hxml.psi.HXMLTypes"
  elementTypeClass="com.intellij.plugins.haxe.buildsystem.hxml.psi.HXMLElementType"
  tokenTypeClass="com.intellij.plugins.haxe.buildsystem.hxml.psi.HXMLTokenType"

  parserUtilClass="com.intellij.plugins.haxe.buildsystem.hxml.parser.HxmlParserUtil"

  generate=[names="short"]

}

simpleFile ::= singleLine* unterminated_line?

private singleLine ::= unterminated_line? endOfLine
private unterminated_line ::= (option | hxmlFile | qualifiedName | unknownValue)   {recoverWhile="line_recovery"}
private line_recovery ::= !(endOfLine)

hxmlFile ::= ((DOTDOT | DOT | IDENTIFER) SLASH)* IDENTIFER (DOT  !<<eofHxmlExtension>> IDENTIFER)* DOT (HXML_EXTENSION | <<eofHxmlExtension>>)
{mixin="com.intellij.plugins.haxe.buildsystem.hxml.psi.mixin.HxmlFileReferenceMixin"}

qualifiedName ::= (IDENTIFER !(HXML_EXTENSION | SLASH) (DOT IDENTIFER)*) | CLASS_NAME
{methods=[getQName]}

private option ::= (lib | define | classpath | main | property | COMMENT)

value ::= path | qualifiedName  | VALUE_TOKEN
private endOfLine ::= CRLF

path ::= (DOTDOT | DOT | IDENTIFER | SLASH)+

key ::= KEY_TOKEN
property ::= key value? {pin=1}

define ::= ('-D'|'--define') value {pin=1}

lib ::= (libHx3|libHx4) value (':' value)? {pin=1}
private libHx3 ::= '-lib'
private libHx4 ::= '-L'|'--library'

classpath ::= (classpathHx3|classpathHx4) value {pin=1}
private classpathHx3 ::= '-cp'
private classpathHx4 ::= '-p'

main ::= (mainHx3| mainHx4) qualifiedName {pin=1}
private mainHx3 ::= '-main'
private mainHx4 ::= '-m'| '--main'

unknownValue ::= UNKNOWN+