// Generated by Haxe 4.0.0-preview.5+7eb789f54
package haxe.root;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class JavaProtocol extends haxe.lang.HxObject
{
	public static void main(String[] args)
	{
		{
			//line 1 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\?"
			haxe.root.JavaProtocol.main();
		}
	}
	
	static
	{
		//line 24 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
		haxe.root.JavaProtocol.IdErrorInternal = 0;
		//line 25 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
		haxe.root.JavaProtocol.IdErrorNoSuchThread = 1;
		//line 26 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
		haxe.root.JavaProtocol.IdErrorNoSuchFile = 2;
		//line 27 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
		haxe.root.JavaProtocol.IdErrorNoSuchBreakpoint = 3;
		//line 28 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
		haxe.root.JavaProtocol.IdErrorBadClassNameRegex = 4;
		//line 29 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
		haxe.root.JavaProtocol.IdErrorBadFunctionNameRegex = 5;
		//line 30 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
		haxe.root.JavaProtocol.IdErrorNoMatchingFunctions = 6;
		//line 31 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
		haxe.root.JavaProtocol.IdErrorBadCount = 7;
		//line 32 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
		haxe.root.JavaProtocol.IdErrorCurrentThreadNotStopped = 8;
		//line 33 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
		haxe.root.JavaProtocol.IdErrorEvaluatingExpression = 9;
		//line 34 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
		haxe.root.JavaProtocol.IdOK = 10;
		//line 35 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
		haxe.root.JavaProtocol.IdExited = 11;
		//line 36 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
		haxe.root.JavaProtocol.IdDetached = 12;
		//line 37 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
		haxe.root.JavaProtocol.IdFiles = 13;
		//line 38 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
		haxe.root.JavaProtocol.IdAllClasses = 14;
		//line 39 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
		haxe.root.JavaProtocol.IdClasses = 15;
		//line 40 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
		haxe.root.JavaProtocol.IdMemBytes = 16;
		//line 41 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
		haxe.root.JavaProtocol.IdCompacted = 17;
		//line 42 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
		haxe.root.JavaProtocol.IdCollected = 18;
		//line 43 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
		haxe.root.JavaProtocol.IdThreadLocation = 19;
		//line 44 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
		haxe.root.JavaProtocol.IdFileLineBreakpointNumber = 20;
		//line 45 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
		haxe.root.JavaProtocol.IdClassFunctionBreakpointNumber = 21;
		//line 46 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
		haxe.root.JavaProtocol.IdBreakpoints = 22;
		//line 47 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
		haxe.root.JavaProtocol.IdBreakpointDescription = 23;
		//line 48 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
		haxe.root.JavaProtocol.IdBreakpointStatuses = 24;
		//line 49 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
		haxe.root.JavaProtocol.IdThreadsWhere = 25;
		//line 50 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
		haxe.root.JavaProtocol.IdVariables = 26;
		//line 51 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
		haxe.root.JavaProtocol.IdValue = 27;
		//line 52 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
		haxe.root.JavaProtocol.IdStructured = 28;
		//line 53 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
		haxe.root.JavaProtocol.IdThreadCreated = 29;
		//line 54 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
		haxe.root.JavaProtocol.IdThreadTerminated = 30;
		//line 55 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
		haxe.root.JavaProtocol.IdThreadStarted = 31;
		//line 56 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
		haxe.root.JavaProtocol.IdThreadStopped = 32;
	}
	
	public JavaProtocol(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public JavaProtocol()
	{
		//line 20 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
		haxe.root.JavaProtocol.__hx_ctor__JavaProtocol(this);
	}
	
	
	protected static void __hx_ctor__JavaProtocol(haxe.root.JavaProtocol __hx_this)
	{
	}
	
	
	public static int IdErrorInternal;
	
	public static int IdErrorNoSuchThread;
	
	public static int IdErrorNoSuchFile;
	
	public static int IdErrorNoSuchBreakpoint;
	
	public static int IdErrorBadClassNameRegex;
	
	public static int IdErrorBadFunctionNameRegex;
	
	public static int IdErrorNoMatchingFunctions;
	
	public static int IdErrorBadCount;
	
	public static int IdErrorCurrentThreadNotStopped;
	
	public static int IdErrorEvaluatingExpression;
	
	public static int IdOK;
	
	public static int IdExited;
	
	public static int IdDetached;
	
	public static int IdFiles;
	
	public static int IdAllClasses;
	
	public static int IdClasses;
	
	public static int IdMemBytes;
	
	public static int IdCompacted;
	
	public static int IdCollected;
	
	public static int IdThreadLocation;
	
	public static int IdFileLineBreakpointNumber;
	
	public static int IdClassFunctionBreakpointNumber;
	
	public static int IdBreakpoints;
	
	public static int IdBreakpointDescription;
	
	public static int IdBreakpointStatuses;
	
	public static int IdThreadsWhere;
	
	public static int IdVariables;
	
	public static int IdValue;
	
	public static int IdStructured;
	
	public static int IdThreadCreated;
	
	public static int IdThreadTerminated;
	
	public static int IdThreadStarted;
	
	public static int IdThreadStopped;
	
	public static void writeServerIdentification(java.io.OutputStream output)
	{
		//line 60 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
		debugger.HaxeProtocol.writeServerIdentification(new _JavaProtocol.OutputAdapter(((java.io.OutputStream) (output) )));
	}
	
	
	public static void readClientIdentification(java.io.InputStream input)
	{
		//line 65 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
		debugger.HaxeProtocol.readClientIdentification(new _JavaProtocol.InputAdapter(((java.io.InputStream) (input) )));
	}
	
	
	public static void writeCommand(java.io.OutputStream output, debugger.Command command)
	{
		//line 71 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
		debugger.HaxeProtocol.writeCommand(new _JavaProtocol.OutputAdapter(((java.io.OutputStream) (output) )), command);
	}
	
	
	public static debugger.Message readMessage(java.io.InputStream input)
	{
		//line 76 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
		return debugger.HaxeProtocol.readMessage(new _JavaProtocol.InputAdapter(((java.io.InputStream) (input) )));
	}
	
	
	public static int getMessageId(debugger.Message message)
	{
		//line 81 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
		switch (message.index)
		{
			case 0:
			{
				//line 82 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				java.lang.String details = haxe.lang.Runtime.toString(message.params[0]);
				//line 83 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				return haxe.root.JavaProtocol.IdErrorInternal;
			}
			
			
			case 1:
			{
				//line 84 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				int number = ((int) (haxe.lang.Runtime.toInt(message.params[0])) );
				//line 85 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				return haxe.root.JavaProtocol.IdErrorNoSuchThread;
			}
			
			
			case 2:
			{
				//line 86 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				java.lang.String fileName = haxe.lang.Runtime.toString(message.params[0]);
				//line 87 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				return haxe.root.JavaProtocol.IdErrorNoSuchFile;
			}
			
			
			case 3:
			{
				//line 88 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				int number1 = ((int) (haxe.lang.Runtime.toInt(message.params[0])) );
				//line 89 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				return haxe.root.JavaProtocol.IdErrorNoSuchBreakpoint;
			}
			
			
			case 4:
			{
				//line 90 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				java.lang.String details1 = haxe.lang.Runtime.toString(message.params[0]);
				//line 91 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				return haxe.root.JavaProtocol.IdErrorBadClassNameRegex;
			}
			
			
			case 5:
			{
				//line 92 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				java.lang.String details2 = haxe.lang.Runtime.toString(message.params[0]);
				//line 93 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				return haxe.root.JavaProtocol.IdErrorBadFunctionNameRegex;
			}
			
			
			case 6:
			{
				//line 94 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				debugger.StringList u = ((debugger.StringList) (message.params[2]) );
				//line 94 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				java.lang.String f = haxe.lang.Runtime.toString(message.params[1]);
				//line 94 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				java.lang.String className = haxe.lang.Runtime.toString(message.params[0]);
				//line 95 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				return haxe.root.JavaProtocol.IdErrorNoMatchingFunctions;
			}
			
			
			case 7:
			{
				//line 96 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				int count = ((int) (haxe.lang.Runtime.toInt(message.params[0])) );
				//line 97 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				return haxe.root.JavaProtocol.IdErrorBadCount;
			}
			
			
			case 8:
			{
				//line 98 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				int threadNumber = ((int) (haxe.lang.Runtime.toInt(message.params[0])) );
				//line 99 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				return haxe.root.JavaProtocol.IdErrorCurrentThreadNotStopped;
			}
			
			
			case 9:
			{
				//line 100 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				java.lang.String details3 = haxe.lang.Runtime.toString(message.params[0]);
				//line 101 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				return haxe.root.JavaProtocol.IdErrorEvaluatingExpression;
			}
			
			
			case 10:
			{
				//line 103 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				return haxe.root.JavaProtocol.IdOK;
			}
			
			
			case 11:
			{
				//line 105 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				return haxe.root.JavaProtocol.IdExited;
			}
			
			
			case 12:
			{
				//line 107 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				return haxe.root.JavaProtocol.IdDetached;
			}
			
			
			case 13:
			{
				//line 108 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				debugger.StringList list = ((debugger.StringList) (message.params[0]) );
				//line 109 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				return haxe.root.JavaProtocol.IdFiles;
			}
			
			
			case 14:
			{
				//line 110 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				debugger.StringList list1 = ((debugger.StringList) (message.params[0]) );
				//line 111 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				return haxe.root.JavaProtocol.IdAllClasses;
			}
			
			
			case 15:
			{
				//line 112 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				debugger.ClassList list2 = ((debugger.ClassList) (message.params[0]) );
				//line 113 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				return haxe.root.JavaProtocol.IdClasses;
			}
			
			
			case 16:
			{
				//line 114 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				int bytes = ((int) (haxe.lang.Runtime.toInt(message.params[0])) );
				//line 115 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				return haxe.root.JavaProtocol.IdMemBytes;
			}
			
			
			case 17:
			{
				//line 116 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				int a = ((int) (haxe.lang.Runtime.toInt(message.params[1])) );
				//line 116 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				int bytesBefore = ((int) (haxe.lang.Runtime.toInt(message.params[0])) );
				//line 117 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				return haxe.root.JavaProtocol.IdCompacted;
			}
			
			
			case 18:
			{
				//line 118 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				int a1 = ((int) (haxe.lang.Runtime.toInt(message.params[1])) );
				//line 118 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				int bytesBefore1 = ((int) (haxe.lang.Runtime.toInt(message.params[0])) );
				//line 119 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				return haxe.root.JavaProtocol.IdCollected;
			}
			
			
			case 19:
			{
				//line 120 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				int l = ((int) (haxe.lang.Runtime.toInt(message.params[5])) );
				//line 120 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				java.lang.String fi = haxe.lang.Runtime.toString(message.params[4]);
				//line 120 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				java.lang.String f1 = haxe.lang.Runtime.toString(message.params[3]);
				//line 120 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				java.lang.String c = haxe.lang.Runtime.toString(message.params[2]);
				//line 120 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				int s = ((int) (haxe.lang.Runtime.toInt(message.params[1])) );
				//line 120 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				int number2 = ((int) (haxe.lang.Runtime.toInt(message.params[0])) );
				//line 121 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				return haxe.root.JavaProtocol.IdThreadLocation;
			}
			
			
			case 20:
			{
				//line 122 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				int number3 = ((int) (haxe.lang.Runtime.toInt(message.params[0])) );
				//line 123 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				return haxe.root.JavaProtocol.IdFileLineBreakpointNumber;
			}
			
			
			case 21:
			{
				//line 124 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				debugger.StringList u1 = ((debugger.StringList) (message.params[1]) );
				//line 124 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				int number4 = ((int) (haxe.lang.Runtime.toInt(message.params[0])) );
				//line 125 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				return haxe.root.JavaProtocol.IdClassFunctionBreakpointNumber;
			}
			
			
			case 22:
			{
				//line 126 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				debugger.BreakpointList list3 = ((debugger.BreakpointList) (message.params[0]) );
				//line 127 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				return haxe.root.JavaProtocol.IdBreakpoints;
			}
			
			
			case 23:
			{
				//line 128 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				debugger.BreakpointLocationList l1 = ((debugger.BreakpointLocationList) (message.params[1]) );
				//line 128 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				int number5 = ((int) (haxe.lang.Runtime.toInt(message.params[0])) );
				//line 129 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				return haxe.root.JavaProtocol.IdBreakpointDescription;
			}
			
			
			case 24:
			{
				//line 130 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				debugger.BreakpointStatusList list4 = ((debugger.BreakpointStatusList) (message.params[0]) );
				//line 131 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				return haxe.root.JavaProtocol.IdBreakpointStatuses;
			}
			
			
			case 25:
			{
				//line 132 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				debugger.ThreadWhereList list5 = ((debugger.ThreadWhereList) (message.params[0]) );
				//line 133 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				return haxe.root.JavaProtocol.IdThreadsWhere;
			}
			
			
			case 26:
			{
				//line 134 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				debugger.StringList list6 = ((debugger.StringList) (message.params[0]) );
				//line 135 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				return haxe.root.JavaProtocol.IdVariables;
			}
			
			
			case 27:
			{
				//line 138 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				java.lang.String v = haxe.lang.Runtime.toString(message.params[2]);
				//line 138 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				java.lang.String t = haxe.lang.Runtime.toString(message.params[1]);
				//line 138 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				java.lang.String expression = haxe.lang.Runtime.toString(message.params[0]);
				//line 139 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				return haxe.root.JavaProtocol.IdValue;
			}
			
			
			case 28:
			{
				//line 136 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				debugger.StructuredValue structuredValue = ((debugger.StructuredValue) (message.params[0]) );
				//line 137 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				return haxe.root.JavaProtocol.IdStructured;
			}
			
			
			case 29:
			{
				//line 140 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				int number6 = ((int) (haxe.lang.Runtime.toInt(message.params[0])) );
				//line 141 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				return haxe.root.JavaProtocol.IdThreadCreated;
			}
			
			
			case 30:
			{
				//line 142 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				int number7 = ((int) (haxe.lang.Runtime.toInt(message.params[0])) );
				//line 143 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				return haxe.root.JavaProtocol.IdThreadTerminated;
			}
			
			
			case 31:
			{
				//line 144 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				int number8 = ((int) (haxe.lang.Runtime.toInt(message.params[0])) );
				//line 145 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				return haxe.root.JavaProtocol.IdThreadStarted;
			}
			
			
			case 32:
			{
				//line 146 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				int l2 = ((int) (haxe.lang.Runtime.toInt(message.params[5])) );
				//line 146 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				java.lang.String fi1 = haxe.lang.Runtime.toString(message.params[4]);
				//line 146 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				java.lang.String f2 = haxe.lang.Runtime.toString(message.params[3]);
				//line 146 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				java.lang.String c1 = haxe.lang.Runtime.toString(message.params[2]);
				//line 146 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				int s1 = ((int) (haxe.lang.Runtime.toInt(message.params[1])) );
				//line 146 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				int number9 = ((int) (haxe.lang.Runtime.toInt(message.params[0])) );
				//line 147 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
				return haxe.root.JavaProtocol.IdThreadStopped;
			}
			
			
		}
		
		//line 79 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
		return 0;
	}
	
	
	public static java.lang.String commandToString(debugger.Command command)
	{
		//line 153 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
		return haxe.root.Std.string(command);
	}
	
	
	public static java.lang.String messageToString(debugger.Message message)
	{
		//line 158 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
		return haxe.root.Std.string(message);
	}
	
	
	public static void main()
	{
		//line 163 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
		java.io.OutputStream stdout = System.out;
		//line 164 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
		debugger.HaxeProtocol.writeMessage(new _JavaProtocol.OutputAdapter(((java.io.OutputStream) (stdout) )), debugger.Message.ThreadsWhere(debugger.ThreadWhereList.Where(0, debugger.ThreadStatus.Running, debugger.FrameList.Frame(true, 0, "h", "i", "p", 10, debugger.FrameList.Terminator), debugger.ThreadWhereList.Terminator)));
		//line 170 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
		haxe.root.Sys.stderr().writeString("Reading message\n", null);
		//line 171 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
		debugger.Message msg = haxe.root.JavaProtocol.readMessage(System.in);
		//line 172 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
		haxe.root.Sys.stderr().writeString("Read message\n", null);
		//line 173 "C:\\Users\\root\\IdeaProjects\\intellij-haxe\\hxcpp-debugger-protocol\\src\\JavaProtocol.hx"
		haxe.root.Sys.stderr().writeString(( ( "Message is: " + haxe.root.Std.string(msg) ) + "\n" ), null);
	}
	
	
}


