{
  parserClass="com.intellij.plugins.haxe.hxml.HXMLParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="HXML"
  psiImplClassSuffix="Impl"
  psiPackage="com.intellij.plugins.haxe.hxml.psi"
  psiImplPackage="com.intellij.plugins.haxe.hxml.psi.impl"

  elementTypeHolderClass="com.intellij.plugins.haxe.hxml.psi.HXMLTypes"
  elementTypeClass="com.intellij.plugins.haxe.hxml.psi.HXMLElementType"
  tokenTypeClass="com.intellij.plugins.haxe.hxml.psi.HXMLTokenType"
}

simpleFile ::= item_*

private item_ ::= (hxml | lib | define | classpath | main | property | qualifiedName | COMMENT | CRLF)

hxml ::= HXML_FILE
property ::= (KEY SEPARATOR VALUE) | KEY {methods=[getKey getValue]}
define ::= '-D' SEPARATOR VALUE
lib ::= '-lib' SEPARATOR VALUE (':' VALUE)? {methods=[getValue]}
classpath ::= '-cp' SEPARATOR VALUE {methods=[getValue]}
main ::= '-main' SEPARATOR qualifiedName

qualifiedName ::= QUALIFIEDCLASSNAME