/*
 * Copyright 2000-2013 JetBrains s.r.o.
 * Copyright 2014-2018 AS3Boyan
 * Copyright 2014-2014 Elias Ku
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by Haxe 3.4.7
package haxe.lang;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class StringRefl
{
	static
	{
		//line 209 "C:\\HaxeToolkit\\haxe\\std\\java\\internal\\StringExt.hx"
		StringRefl.fields = new haxe.root.Array<String>(new String[]{"length", "toUpperCase", "toLowerCase", "charAt", "charCodeAt", "indexOf", "lastIndexOf", "split", "substr", "substring"});
	}
	
	public StringRefl()
	{
	}
	
	
	public static haxe.root.Array<String> fields;
	
	public static Object handleGetField(String str, String f, boolean throwErrors)
	{
		//line 213 "C:\\HaxeToolkit\\haxe\\std\\java\\internal\\StringExt.hx"
		{
			//line 213 "C:\\HaxeToolkit\\haxe\\std\\java\\internal\\StringExt.hx"
			String __temp_svar1 = (f);
			//line 213 "C:\\HaxeToolkit\\haxe\\std\\java\\internal\\StringExt.hx"
			int __temp_hash3 = __temp_svar1.hashCode();
			//line 213 "C:\\HaxeToolkit\\haxe\\std\\java\\internal\\StringExt.hx"
			boolean __temp_executeDef2 = true;
			//line 213 "C:\\HaxeToolkit\\haxe\\std\\java\\internal\\StringExt.hx"
			switch (__temp_hash3)
			{
				case -1106363674:
				{
					//line 213 "C:\\HaxeToolkit\\haxe\\std\\java\\internal\\StringExt.hx"
					if (__temp_svar1.equals("length")) 
					{
						//line 213 "C:\\HaxeToolkit\\haxe\\std\\java\\internal\\StringExt.hx"
						__temp_executeDef2 = false;
						//line 215 "C:\\HaxeToolkit\\haxe\\std\\java\\internal\\StringExt.hx"
						return str.length();
					}
					
					//line 213 "C:\\HaxeToolkit\\haxe\\std\\java\\internal\\StringExt.hx"
					break;
				}
				
				
				case -399551817:
				case -1137582698:
				case 530542161:
				case -891529231:
				case 109648666:
				case -467511597:
				case 1943291465:
				case 397153782:
				case -1361633751:
				{
					//line 213 "C:\\HaxeToolkit\\haxe\\std\\java\\internal\\StringExt.hx"
					if (( (( ( __temp_hash3 == -399551817 ) && __temp_svar1.equals("toUpperCase") )) || ( (( ( __temp_hash3 == -1137582698 ) && __temp_svar1.equals("toLowerCase") )) || ( (( ( __temp_hash3 == 530542161 ) && __temp_svar1.equals("substring") )) || ( (( ( __temp_hash3 == -891529231 ) && __temp_svar1.equals("substr") )) || ( (( ( __temp_hash3 == 109648666 ) && __temp_svar1.equals("split") )) || ( (( ( __temp_hash3 == -467511597 ) && __temp_svar1.equals("lastIndexOf") )) || ( (( ( __temp_hash3 == 1943291465 ) && __temp_svar1.equals("indexOf") )) || ( (( ( __temp_hash3 == 397153782 ) && __temp_svar1.equals("charCodeAt") )) || __temp_svar1.equals("charAt") ) ) ) ) ) ) ) )) 
					{
						//line 213 "C:\\HaxeToolkit\\haxe\\std\\java\\internal\\StringExt.hx"
						__temp_executeDef2 = false;
						//line 217 "C:\\HaxeToolkit\\haxe\\std\\java\\internal\\StringExt.hx"
						return new Closure(str, f);
					}
					
					//line 213 "C:\\HaxeToolkit\\haxe\\std\\java\\internal\\StringExt.hx"
					break;
				}
				
				
			}
			
			//line 219 "C:\\HaxeToolkit\\haxe\\std\\java\\internal\\StringExt.hx"
			if (__temp_executeDef2) 
			{
				//line 219 "C:\\HaxeToolkit\\haxe\\std\\java\\internal\\StringExt.hx"
				if (throwErrors) 
				{
					//line 220 "C:\\HaxeToolkit\\haxe\\std\\java\\internal\\StringExt.hx"
					throw haxe.lang.HaxeException.wrap(( ( "Field not found: \'" + f ) + "\' in String" ));
				}
				else
				{
					//line 222 "C:\\HaxeToolkit\\haxe\\std\\java\\internal\\StringExt.hx"
					return null;
				}
				
			}
			else
			{
				//line 219 "C:\\HaxeToolkit\\haxe\\std\\java\\internal\\StringExt.hx"
				throw null;
			}
			
		}
		
	}
	
	
	public static Object handleCallField(String str, String f, haxe.root.Array args)
	{
		//line 228 "C:\\HaxeToolkit\\haxe\\std\\java\\internal\\StringExt.hx"
		haxe.root.Array _args = new haxe.root.Array(new Object[]{str});
		//line 229 "C:\\HaxeToolkit\\haxe\\std\\java\\internal\\StringExt.hx"
		if (( args == null )) 
		{
			//line 230 "C:\\HaxeToolkit\\haxe\\std\\java\\internal\\StringExt.hx"
			args = _args;
		}
		else
		{
			//line 232 "C:\\HaxeToolkit\\haxe\\std\\java\\internal\\StringExt.hx"
			args = _args.concat(args);
		}
		
		//line 234 "C:\\HaxeToolkit\\haxe\\std\\java\\internal\\StringExt.hx"
		return Runtime.slowCallField(StringExt.class, f, args);
	}
	
	
}


