/*
 * Copyright 2000-2013 JetBrains s.r.o.
 * Copyright 2014-2018 AS3Boyan
 * Copyright 2014-2014 Elias Ku
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by Haxe 3.4.7
package _List;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class ListNode<T> extends haxe.lang.HxObject
{
	public ListNode(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public ListNode(T item, ListNode<T> next)
	{
		//line 255 "C:\\HaxeToolkit\\haxe\\std\\List.hx"
		ListNode.__hx_ctor__List_ListNode(((ListNode<T>) (this) ), ((T) (item) ), ((ListNode<T>) (next) ));
	}
	
	
	public static <T_c> void __hx_ctor__List_ListNode(ListNode<T_c> __hx_this, T_c item, ListNode<T_c> next)
	{
		//line 256 "C:\\HaxeToolkit\\haxe\\std\\List.hx"
		__hx_this.item = item;
		//line 257 "C:\\HaxeToolkit\\haxe\\std\\List.hx"
		__hx_this.next = next;
	}
	
	
	public T item;
	
	public ListNode<T> next;
	
	@Override public double __hx_setField_f(String field, double value, boolean handleProperties)
	{
		//line 252 "C:\\HaxeToolkit\\haxe\\std\\List.hx"
		{
			//line 252 "C:\\HaxeToolkit\\haxe\\std\\List.hx"
			boolean __temp_executeDef1 = true;
			//line 252 "C:\\HaxeToolkit\\haxe\\std\\List.hx"
			switch (field.hashCode())
			{
				case 3242771:
				{
					//line 252 "C:\\HaxeToolkit\\haxe\\std\\List.hx"
					if (field.equals("item")) 
					{
						//line 252 "C:\\HaxeToolkit\\haxe\\std\\List.hx"
						__temp_executeDef1 = false;
						//line 252 "C:\\HaxeToolkit\\haxe\\std\\List.hx"
						this.item = ((T) (((Object) (value) )) );
						//line 252 "C:\\HaxeToolkit\\haxe\\std\\List.hx"
						return ((double) (haxe.lang.Runtime.toDouble(((Object) (value) ))) );
					}
					
					//line 252 "C:\\HaxeToolkit\\haxe\\std\\List.hx"
					break;
				}
				
				
			}
			
			//line 252 "C:\\HaxeToolkit\\haxe\\std\\List.hx"
			if (__temp_executeDef1) 
			{
				//line 252 "C:\\HaxeToolkit\\haxe\\std\\List.hx"
				return super.__hx_setField_f(field, value, handleProperties);
			}
			else
			{
				//line 252 "C:\\HaxeToolkit\\haxe\\std\\List.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public Object __hx_setField(String field, Object value, boolean handleProperties)
	{
		//line 252 "C:\\HaxeToolkit\\haxe\\std\\List.hx"
		{
			//line 252 "C:\\HaxeToolkit\\haxe\\std\\List.hx"
			boolean __temp_executeDef1 = true;
			//line 252 "C:\\HaxeToolkit\\haxe\\std\\List.hx"
			switch (field.hashCode())
			{
				case 3377907:
				{
					//line 252 "C:\\HaxeToolkit\\haxe\\std\\List.hx"
					if (field.equals("next")) 
					{
						//line 252 "C:\\HaxeToolkit\\haxe\\std\\List.hx"
						__temp_executeDef1 = false;
						//line 252 "C:\\HaxeToolkit\\haxe\\std\\List.hx"
						this.next = ((ListNode<T>) (value) );
						//line 252 "C:\\HaxeToolkit\\haxe\\std\\List.hx"
						return value;
					}
					
					//line 252 "C:\\HaxeToolkit\\haxe\\std\\List.hx"
					break;
				}
				
				
				case 3242771:
				{
					//line 252 "C:\\HaxeToolkit\\haxe\\std\\List.hx"
					if (field.equals("item")) 
					{
						//line 252 "C:\\HaxeToolkit\\haxe\\std\\List.hx"
						__temp_executeDef1 = false;
						//line 252 "C:\\HaxeToolkit\\haxe\\std\\List.hx"
						this.item = ((T) (value) );
						//line 252 "C:\\HaxeToolkit\\haxe\\std\\List.hx"
						return value;
					}
					
					//line 252 "C:\\HaxeToolkit\\haxe\\std\\List.hx"
					break;
				}
				
				
			}
			
			//line 252 "C:\\HaxeToolkit\\haxe\\std\\List.hx"
			if (__temp_executeDef1) 
			{
				//line 252 "C:\\HaxeToolkit\\haxe\\std\\List.hx"
				return super.__hx_setField(field, value, handleProperties);
			}
			else
			{
				//line 252 "C:\\HaxeToolkit\\haxe\\std\\List.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public Object __hx_getField(String field, boolean throwErrors, boolean isCheck, boolean handleProperties)
	{
		//line 252 "C:\\HaxeToolkit\\haxe\\std\\List.hx"
		{
			//line 252 "C:\\HaxeToolkit\\haxe\\std\\List.hx"
			boolean __temp_executeDef1 = true;
			//line 252 "C:\\HaxeToolkit\\haxe\\std\\List.hx"
			switch (field.hashCode())
			{
				case 3377907:
				{
					//line 252 "C:\\HaxeToolkit\\haxe\\std\\List.hx"
					if (field.equals("next")) 
					{
						//line 252 "C:\\HaxeToolkit\\haxe\\std\\List.hx"
						__temp_executeDef1 = false;
						//line 252 "C:\\HaxeToolkit\\haxe\\std\\List.hx"
						return this.next;
					}
					
					//line 252 "C:\\HaxeToolkit\\haxe\\std\\List.hx"
					break;
				}
				
				
				case 3242771:
				{
					//line 252 "C:\\HaxeToolkit\\haxe\\std\\List.hx"
					if (field.equals("item")) 
					{
						//line 252 "C:\\HaxeToolkit\\haxe\\std\\List.hx"
						__temp_executeDef1 = false;
						//line 252 "C:\\HaxeToolkit\\haxe\\std\\List.hx"
						return this.item;
					}
					
					//line 252 "C:\\HaxeToolkit\\haxe\\std\\List.hx"
					break;
				}
				
				
			}
			
			//line 252 "C:\\HaxeToolkit\\haxe\\std\\List.hx"
			if (__temp_executeDef1) 
			{
				//line 252 "C:\\HaxeToolkit\\haxe\\std\\List.hx"
				return super.__hx_getField(field, throwErrors, isCheck, handleProperties);
			}
			else
			{
				//line 252 "C:\\HaxeToolkit\\haxe\\std\\List.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public double __hx_getField_f(String field, boolean throwErrors, boolean handleProperties)
	{
		//line 252 "C:\\HaxeToolkit\\haxe\\std\\List.hx"
		{
			//line 252 "C:\\HaxeToolkit\\haxe\\std\\List.hx"
			boolean __temp_executeDef1 = true;
			//line 252 "C:\\HaxeToolkit\\haxe\\std\\List.hx"
			switch (field.hashCode())
			{
				case 3242771:
				{
					//line 252 "C:\\HaxeToolkit\\haxe\\std\\List.hx"
					if (field.equals("item")) 
					{
						//line 252 "C:\\HaxeToolkit\\haxe\\std\\List.hx"
						__temp_executeDef1 = false;
						//line 252 "C:\\HaxeToolkit\\haxe\\std\\List.hx"
						return ((double) (haxe.lang.Runtime.toDouble(((Object) (this.item) ))) );
					}
					
					//line 252 "C:\\HaxeToolkit\\haxe\\std\\List.hx"
					break;
				}
				
				
			}
			
			//line 252 "C:\\HaxeToolkit\\haxe\\std\\List.hx"
			if (__temp_executeDef1) 
			{
				//line 252 "C:\\HaxeToolkit\\haxe\\std\\List.hx"
				return super.__hx_getField_f(field, throwErrors, handleProperties);
			}
			else
			{
				//line 252 "C:\\HaxeToolkit\\haxe\\std\\List.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public void __hx_getFields(haxe.root.Array<String> baseArr)
	{
		//line 252 "C:\\HaxeToolkit\\haxe\\std\\List.hx"
		baseArr.push("next");
		//line 252 "C:\\HaxeToolkit\\haxe\\std\\List.hx"
		baseArr.push("item");
		//line 252 "C:\\HaxeToolkit\\haxe\\std\\List.hx"
		super.__hx_getFields(baseArr);
	}
	
	
}


