name: Build, IntelliJ-Haxe-plugin

on:
  push:
    branches:
      - 'master'
      - 'develop'
      - 'feature/*'
  pull_request:
    branches:
      - 'master'
      - 'develop'
      - 'feature/*'

jobs:
  Build:
    strategy:
      fail-fast: false # set this to true if you want to cancel all builds if one fails.
      matrix:
        IDEA_VERSION: [2025.2.1]
        OS: [macos-13, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.OS }}
    timeout-minutes: 25
    steps:
      - name: Maximize Build Space (ubuntu/mac)
        if: ${{ matrix.os != 'windows-latest'}}
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc

      - uses: actions/checkout@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 21
          cache: 'gradle'


      - name: Set up Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.4

      - name: Test haxe
        run: haxe -version


      - name: Cache intelliJ downloads
        uses: actions/cache@v4
        with:
          path: $GITHUB_WORKSPACE/idea
          key: ${{ matrix.IDEA_VERSION }}-idea
          restore-keys: ${{ matrix.IDEA_VERSION }}-idea


      - name: Build with Gradle (windows)
        timeout-minutes: 25
        if: ${{ matrix.os == 'windows-latest'}}
        run: .\gradlew.bat clean test buildPlugin verifyPlugin

      - name: Build with Gradle (linux/mac)
        timeout-minutes: 25
        if: ${{ matrix.os != 'windows-latest'}}
        run: ./gradlew clean test buildPlugin verifyPlugin


